Email whitelisting feature
Fliplet/fliplet-widget-validation-manager pull request #4
Opened 2017-06-07 15:50 UTC by seromenho

2017-06-07 16:40 UTC, tonytlwu requested changes

2017-06-07 16:40 UTC, tonytlwu commented on interface.html
> +      <div class="col-sm-12 email-domains-input hidden">
This should be wrapped around `<div class="form-group"></div>` the you won't need `.email-domains-input { margin-top: 10px; }` in `interface.css`.

2017-06-07 16:40 UTC, tonytlwu commented on js/interface.js
> +  default:
What would happen in this case? Will it continue to pass an empty object `{}` to the DS Query provider? Will this create an error? Maybe the error should either be handled, or `default` to the same case as `email`?

2017-06-08 14:57 UTC, seromenho commented on interface.html
> +      <div class="col-sm-12 email-domains-input hidden">
@hcarneiro ^^ would you mind?

2017-06-08 15:02 UTC, seromenho commented on js/interface.js
> +  default:
Good point. email/default are now the same.

2017-06-15 10:43 UTC, hcarneiro approved these changes

2017-06-15 10:49 UTC, merged